name: Build and release Positive Vibes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (main)
        uses: actions/checkout@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      - name: Checkout (staging)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
        if: ${{ github.event_name == 'workflow_dispatch' }}
      - name: Get current version
        run: |
          echo "RELEASE_VERSION=$(npm pkg get version)"
          echo "RELEASE_VERSION=$(npm pkg get version)" >> $GITHUB_ENV
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install wine
        run: |
          sudo dpkg --add-architecture i386
          sudo mkdir -pm755 /etc/apt/keyrings
          sudo wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
          sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/winehq-jammy.sources
          sudo apt-get update
          sudo apt-get install --install-recommends winehq-stable
      - name: Build Windows
        run: |
          pnpm clean
          pnpm package-win
      - name: Build Linux
        run: |
          pnpm package-linux
      - name: Release (main)
        uses: softprops/action-gh-release@v2
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        env:
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
        with:
          files: |
            build/*
            !**/*.yml
            !**/*.yaml
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ env.RELEASE_VERSION }}
          tag_name: v${{ env.RELEASE_VERSION }}
      - name: Release (staging)
        uses: softprops/action-gh-release@v2
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
        with:
          files: |
            build/*
            !**/*.yml
            !**/*.yaml
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ env.RELEASE_VERSION }}.${{ github.sha }}
          tag_name: v${{ env.RELEASE_VERSION }}.${{ github.sha }}
          prerelease: true
