name: Build and release Positive Vibes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get current version
        id: get_version
        run: echo ::set-output name=VERSION::$(npm pkg get version)
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install wine
        run: |
          sudo dpkg --add-architecture i386
          sudo mkdir -pm755 /etc/apt/keyrings
          sudo wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
          sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/winehq-jammy.sources
          sudo apt-get update
          sudo apt-get install --install-recommends winehq-stable
      - name: Build Windows
        run: |
          pnpm clean
          pnpm package-win
      - name: Release (main)
        uses: softprops/action-gh-release@v2
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          files: build/*
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ steps.get_version.outputs.VERSION }}
      - name: Release (staging)
        uses: softprops/action-gh-release@v2
        if: ${{ github.event_name == 'workflow_dispatch' }}
        with:
          files: build/*
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ steps.get_version.outputs.VERSION }}.${{ github.sha }}
          prerelease: true
